### ISSUE TITLE
How to handle documents

### ISSUE THREAD

**Issue by wooorm** [syntax-tree/hast-util-to-mdast#1]
HAST can represent documents, e.g.,

```html
<!doctype html>
<html>
  <head><meta charset="utf8"></head>
  <body><p>Text</p></body>
</html>
```

...but also:

```html
<!doctype html>
<meta charset="utf8">
<p>Text</p>
```

Another interesting case is:

```html
<!doctype html>
<html>
  <head><meta charset="utf8"></head>
  <body>
    <header>Random stuff</header>
    <main>Core</main>
    <footer>More random stuff</footer>
  </body>
</html>
```

...how should the core contents be handled? Should `hast-util-to-mdast` search for the `body` element, or even the `main`, or some other things? I remember there’s a class you can add to the main content to let Instapaper recognise it, I couldn’t find it when searching just now, but maybe something like that is interesting too.

**Comment by omarchehab98** [comment]
W3C spec requires [`main`](https://developer.mozilla.org/en/docs/Web/HTML/Element/main) to be used once throughout the document. Also, it requires it to contain unique content. Therefore, I would not worry about:

> there’s a class you can add to the main content to let Instapaper recognise it, I couldn’t find it when searching just now

I would approach this by searching for `main` and falling back to `body`.

**Comment by wooorm** [comment]
Thanks for giving your thoughts on this!

What I’m mainly wondering about, and I don’t think the above gave that away, is whether `hast-util-to-mdast` should try to extract the “article” from content, thus ignoring “aside” content.

But I don’t think that’s possible to do properly in all cases. And I think some other tool can probably do it better, and this behaviour *should* be in some other program!
