### ISSUE TITLE
<br /> tag doesn't compile to new line in <code />

### ISSUE THREAD

**Issue by juhaelee** [syntax-tree/hast-util-to-mdast#39]
I'm trying to compile the following html to markdown:

```html
<pre class="language-javascript"><code class="language-javascript">var x = &quot;hi&quot;;<br/>var y = &quot;hi&quot;;<br/>var z = &quot;hi&quot;;<br/>var a = &quot;hi&quot;;<br/></code></pre>
```

however, when i run this html string through rehype-remark, it removes the `<br />` tags and hands me markdown that looks like this:
```javascript
var x = "hi";var y = "hi";var z = "hi";var a = "hi";
```

Original question asked [on spectrum here](https://spectrum.chat/notifications?thread=c3ed06ab-d606-43a8-b226-a0a1fdef576c)

**Comment by wooorm** [comment]
What we’re doing currently is follow the [`textContent`](https://dom.spec.whatwg.org/#dom-node-textcontent) algorithm as specified by the DOM.

What you’re asking for is the [`innerText` algorithm](https://html.spec.whatwg.org/#the-innertext-idl-attribute). This one takes `<br>` elements into account.

I don’t think there are other elements that need this specific handling.
