### ISSUE TITLE
<br> in tables breaks table

### ISSUE THREAD

**Issue by thisconnect** [syntax-tree/hast-util-to-mdast#56]
### Subject of the issue

table is lost in mdast if `<td>` or `<th>` elements contain a `<br>` 

### Your environment

*   **OS**: macos
*   **Packages**:  `hast-util-to-mdast@5.0.1` through `rehype-remark@6.0.0` 
*   **Env**: Node.js v12.7.0, NPM 6.11.2

### Steps to reproduce

https://github.com/syntax-tree/hast-util-to-mdast/pull/57/files

### Expected behaviour

table is still preserved, even with `<br>`

I am not 100% sure what the best solution would be, maybe just drop the `<br>` ?

### Actual behaviour

output of tables containing `<br>` seems to loose the table info

**Comment by thisconnect** [comment]
added test https://github.com/syntax-tree/hast-util-to-mdast/pull/57/files

**Comment by wooorm** [comment]
Hey @thisconnect. Thanks for raising this, [but please fill out the form that you deleted](https://raw.githubusercontent.com/syntax-tree/.github/master/.github/ISSUE_TEMPLATE/1-bug.md). It helps us help you

**Comment by thisconnect** [comment]
@wooorm sorry, I just deleted it without thinking :) added back the form to the description https://github.com/syntax-tree/hast-util-to-mdast/issues/56#issue-484806141

**Comment by wooorm** [comment]
Thanks! I think this should go in `remark-stringify`, it shouldn’t output line feeds in cells 🤔

**Comment by thisconnect** [comment]
thanks
