### ISSUE TITLE
Discrepancy in dependency

### ISSUE THREAD

**Issue by agix** [syntax-tree/hast-util-to-mdast#61]
### Subject of the issue

Crash here when using `rehype-remark` https://github.com/syntax-tree/hast-util-to-mdast/blob/7.1.2/lib/handlers/code.js#L6

It seems you forgot to bump package.json for lib `hast-util-is-element` cause 1.0.x doesn't contain `convert` file.

https://github.com/syntax-tree/hast-util-is-element/tree/1.0.4

I think you can solve the issue by publishing a new tag with updated package.json with hast-util-is-element on  `^1.1.0`

### Steps to reproduce

I don't really know why `yarn` sometimes pick `1.0.x` and sometimes `1.1.x` based on the instruction `^1.0.0`

In the first case, it breaks, in the second it works.

**Comment by wooorm** [comment]
Thanks, fixed!

**Comment by entr** [comment]
I see 7.1.3 tagged, but it's not published...?

**Comment by wooorm** [comment]
weird, I just published it
