### ISSUE TITLE
Nested tables creates empty cells

### ISSUE THREAD

**Issue by tripodsan** [syntax-tree/hast-util-to-mdast#65]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

hast-util-to-mdast 8.2.0 and 7.1.3

### Steps to reproduce

create a nested table that has more cells than the parent table.
the `inspect()` function in the `table` handler calculates the total _width_ of the table,
but doesn't stop the traversal inside the cell. 

when the cell has a nested table, it messes up the `rowIndex` and `cellIndex` calculations.

IMO, it should use `visit.SKIP` in the `cell` case:
https://github.com/syntax-tree/hast-util-to-mdast/blob/1fcbbf75d914e6f84adca0628b44bd647087a00b/lib/handlers/table.js#L122

### Expected behavior

calculates the number of columns correctly.

### Actual behavior

inserts empty cells if a nested table has more cells.

### Runtime

Node v12

### Package manager

npm v7

### OS

macOS

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by wooorm** [comment]
Hmm, interesting!
Could you produce a smallest possible example that reproduces this, that helps me work on a fix!

**Comment by tripodsan** [comment]
FWIW, it would be cool to have an option to disable the headless mode. i.e. the extra row when the `thead` is missing.

**Comment by wooorm** [comment]
OK that will help, thanks! But now to figure out: how *should* it work? How should nested tables be rendered in markdown? 🤔

For the "headless mode", that would result in invalid markdown though?

**Comment by tripodsan** [comment]
> OK that will help, thanks! But now to figure out: how _should_ it work? How should nested tables be rendered in markdown? 🤔

good question :-)

our use case is that we have a mixed md/html that we parse and transform it further into a docx.
especially because md doesn't support nested tables, we use html tables. and then have a special html handler that generates nested md tables.

> For the "headless mode", that would result in invalid markdown though?

yes. that's true. the problem is sloppy defined HTML tables, that don't have a header. so we would just use the first row as header. it's not a big problem.

**Comment by wooorm** [comment]
> and then have a special html handler that generates nested md tables.

You serialize the nested table as HTML, inside a “markdown” table cell I guess?

> so we would just use the first row as header. but it's not important.

The current code can infer `th` cells in a first row — because `thead` is not needed according to HTML.
But I’d say sloppy input may result sloppy output — and it’s also something that can be handled before/after by you if you want to fix it

**Comment by tripodsan** [comment]
> > and then have a special html handler that generates nested md tables.
> 
> You serialize the nested table as HTML, inside a “markdown” table cell I guess?

first, yes. but then it looked weird and is not easy readable anyways. now we use only HTML tables, which is enough for our use case.

we also looked into [grid-tables](https://pandoc.org/MANUAL.html#extension-grid_tables) and also into custom directives, but using HTML is easier.

> > so we would just use the first row as header. but it's not important.
> 
> The current code can infer `th` cells in a first row — because `thead` is not needed according to HTML.
> But I’d say sloppy input may result sloppy output — and it’s also something that can be handled before/after by you if you want to fix it

true :-)

**Comment by wooorm** [comment]
Released a fix!
