### ISSUE TITLE
ignoring non-standard html tags

### ISSUE THREAD

**Issue by giorgio-zamparelli** [syntax-tree/hast-util-to-mdast#78]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

The option handlers allows to keep some html tags like explained here: [Example: keeping some HTML](https://github.com/syntax-tree/hast-util-to-mdast#example-keeping-some-html) with <svg>
How can I keep all-non stardard html tags?
In my use case I need to keep all-standard html tags that a user defines.
This is because the non-standard html tags are actually JSX tags inside of a mdx file.

TAGS TO CONVERT
```
<h1>
<p>
...
```

TAGS TO KEEP
```
<custom-tag>
<note>
<JsxWannabe>
```

### Solution

Add support for an html attribute **data-mnast="keep"**
Like the data-mdast="ignore" but it keeps the tag as it is instead of ignoring it.
`<custom-tag data-mdast="keep">`

### Alternatives

I see 2 possible alternatives:
1) Add an option that keeps all non-standard html tags

2) passing a wildcard function to handlers option that doesn't specify the matching tag but will ran on everythig:
It could be called: all, *, default or something else
```
handlers: {
  all: (h, node, tag) => {

    if (allStandardTags.includes(tag)) {
      // convert it normally to markdown
      
    } else {
      // keep it as html
      return h(node, 'html', toHtml(node))
    }
  },
},
```

**Comment by ChristianMurphy** [comment]
See https://github.com/orgs/rehypejs/discussions/125#discussioncomment-4943055
Both for commentary on `<note>` and `<JsxWannabe>`, as well as a potential solution which does not require attributes to be added to elements.

**Comment by wooorm** [comment]
There may be a good reason to add such a feature, but the underlying problem posted here is unrelated to this feature.

As you are dealing with MDX, you should not use an HTML parser, but an MDX parser.
You can use `remark` together with `remark-mdx` (or `markdown-rs` / `micromark` / `mdast-util-from-markdown` etc) to parse MDX, at which point you have a nice AST!
