### ISSUE TITLE
List item spread calculates spread incorrectly with nested lists.

### ISSUE THREAD

**Issue by TRIAEIOU** [syntax-tree/hast-util-to-mdast#79]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

9.0.0

### Steps to reproduce

With nested lists li.js [spreadout](https://github.com/syntax-tree/hast-util-to-mdast/blob/08be0e15246a59a426be515111012603722c2af1/lib/handlers/li.js#L80) incorrectly calculates spread when using a nested list with multiple items as far as I can tell.

```js
import { toMdast } from "hast-util-to-mdast";
const hast = {
  type: "root",
  children: [
    {
      type: "element",
      tagName: "ul",
      children: [
        {
          type: "element",
          tagName: "li",
          properties: {},
          children: [
            {
              type: "text",
              value: "outer",
            },
            {
              type: "element",
              tagName: "ul",
              children: [
                {
                  type: "element",
                  tagName: "li",
                  properties: {},
                  children: [
                    {
                      type: "text",
                      value: "inner",
                    },
                  ],
                },
                {
                  type: "element",
                  tagName: "li",
                  properties: {},
                  children: [
                    {
                      type: "text",
                      value: "inner",
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: "element",
      tagName: "li",
      properties: {},
      children: [
        {
          type: "text",
          value: "outer",
        },
      ],
    },
  ],
};
const mdast = toMdast(hast);
console.log(JSON.stringify(mdast));
```

### Expected behavior

Both the outer and inner lists should be [`tight`](https://spec.commonmark.org/0.30/#lists).

### Actual behavior

The outer list is flagged as `loose`, as far as I can tell due to [L94](https://github.com/syntax-tree/hast-util-to-mdast/blob/08be0e15246a59a426be515111012603722c2af1/lib/handlers/li.js#L94) which, as far as I can tell, should read `seenFlow = child.tagName !== 'ul' && child.tagName !== 'ol' && child.tagName !== 'li'` instead.

### Affected runtime and version

18.2.0

### Affected package manager and version

8.6.0

### Affected OS and version

Windows 11

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by TRIAEIOU** [comment]
Hi, 

> Why?
> You provide no reasoning for why you think some things are wrong and some things are right.

You are correct, I apologize. In the case of nested lists the current implementation, as far as I can tell, makes it impossible to create a tight outer list from HTML. For instance the commonmark spec [319](https://spec.commonmark.org/0.30/#example-319) becomes impossible to reverse.

Another example would be the following in the commonmark [dingus](https://spec.commonmark.org/dingus/?text=-%20outer%0A%20%20-%20inner%0A%20%20-%20inner%0A-%20outer)
```
- outer
  - inner
  - inner
- outer
```
The dingus renders this as `<ul><li>outer<ul><li>inner</li><li>inner</li></ul></li><li>outer</li></ul>`, i.e. both lists are tight and reversing this becomes impossible with current implementation.

> The variable seenFlow represents whether flow was seen.
> Lists are flow content.
> So I think it is logical that seenFlow is set to true for ol and ul.

Understood, I am looking at the net effect - the outer list of any nested list always becoming `loose` (as far as I can tell, also see below).

> `li` will never occur directly inside another `li`, so it’s not needed to check for that there.

You are correct, I was a bit quick when adding that to the condition.

Besides missing supplying the motivation it seems I also copy/pasted incorrectly in my sample, here is a version with less risk of error:
```js
import { toMdast } from "hast-util-to-mdast";
import { toMarkdown } from "mdast-util-to-markdown";
import { fromHtml } from "hast-util-from-html";

const html = `<ul>
<li>outer
    <ul>
      <li>inner</li>
      <li>inner</li>
    </ul>
  </li>
  <li>outer</li>
</ul>`

const hast = fromHtml(html)
const mdast = toMdast(hast)
const md = toMarkdown(mdast)
console.log(md);
```

With the current implementation this results in the following output:
```markdown
*   outer

    *   inner
    *   inner

*   outer

```

With with `seenFlow = node.tagName !== 'ol' && node.tagName != 'ul'` it becomes
```markdown
*   outer
    *   inner
    *   inner
*   outer

```

To me it seems that 319 hints at, and the implementation logic in the dingus shows, something like `loose if containing two consecutive non-list block elements`. 

Thoughts?

**Comment by TRIAEIOU** [comment]
> I prefer the first (current). I think the second does not look clear. I do not recommend people to write markdown without using blank lines.

Fair enough, although to me it seems the spec allows you to do either
```markdown
- outer
  - inner
  - inner
- outer
```
resulting in
```html
<ul>
<li>outer
<ul>
<li>inner</li>
<li>inner</li>
</ul>
</li>
<li>outer</li>
</ul>
```

_or_

```markdown
- outer

  - inner
  - inner

- outer
```

resulting in:

```html
<ul>
<li>
<p>outer</p>
<ul>
<li>inner</li>
<li>inner</li>
</ul>
</li>
<li>
<p>outer</p>
</li>
</ul>
```

So I think it would be preferable/"closer to spec" to have a similar logic for the reverse, i.e. have the user decide by what the input html looks like.

Let me know which way you decide to go and feel free to cancel/reject the bug report (playing with the code there seems to be another issue that needs to be solved as well for this to "fixed", somewhere in `toMdast` it seems some `li` nodes with `text` children are converted to paragraphs prior to `spreadout()` being called but I am not certain, currently investigating it).

Cheers!

**Comment by wooorm** [comment]
There are many, many combinations possible (with or without blank lines):

```
- # a
  - b
```

```
- > a
  - b
```

```
- ~~~a
  ~~~
  - b
```

```
-     a
  - b
```

```
- [a]: b
  - c
```

```
- * a
  1. b
```

```
- | a |
  | - |
  - b
```

And this is only when combined with a list, which is not needed.

You focus on lists, but your issue is not about lists.
It’s about paragraphs combined with other things.
If you want to improve the situation for that case (which to me feels a bit pointless, because there are so many cases where paragraphs aren’t used), I think the direction of a solution would be around paragraphs.

**Comment by TRIAEIOU** [comment]
> You focus on lists, but your issue is not about lists.

How do you mean?

Regardless, point taken, the issue is fairly easy to address locally for my needs so let's drop this.

**Comment by wooorm** [comment]
> How do you mean?

Your issue title is `with nested lists`, indicating that there is an issue with lists.

Here’s an example without lists:

```markdown
* # a
  # b
```

```markdown
* # a

  # b
```

First is tight, second is loose. Impossible to roundtrip. Your proposal does make this case “roundtrippable”.

Here’s an example with lists:

```markdown
* - a
  + b
```

```markdown
* - a

  + b
```

First is tight, second is loose. Impossible to roundtrip. Your proposal does make this case “roundtrippable”.

And that’s why I start with the question:

> > Both the outer and inner lists should be tight
>
> Why?
> You provide no reasoning for why you think some things are wrong and some things are right.

You propose ignoring lists. That changes from one version to the other. But it doesn’t bring anything closer to CommonMark. It changes things, but it doesn’t improve things.

There is only one case where we can detect if something was written loosely/tightly: if there were `p`s. Which resulted either in `p`s, or in phrasing content. Which is this check:

https://github.com/syntax-tree/hast-util-to-mdast/blob/08be0e15246a59a426be515111012603722c2af1/lib/handlers/li.js#L90
